import { Mail, MapPin, Shield } from "lucide-react";
import PageHeader from "@/components/PageHeader";
import GlassCard from "@/components/GlassCard";

const Contact = () => {
  return (
    <div className="min-h-screen pt-24 pb-16">
      <div className="container mx-auto px-4">
        <PageHeader
          icon={<Mail className="w-7 h-7 text-primary" />}
          title="Contact & Disclaimer"
          subtitle="Academic usage information, institutional context, and privacy notices."
        />

        <div className="max-w-3xl mx-auto space-y-8">
          {/* Disclaimer */}
          <GlassCard hover={false}>
            <div className="flex items-start gap-4">
              <div className="w-10 h-10 rounded-xl bg-risk-moderate/10 flex items-center justify-center shrink-0">
                <Shield className="w-5 h-5 text-risk-moderate" />
              </div>
              <div>
                <h3 className="font-display font-semibold text-foreground mb-2">Academic Usage Disclaimer</h3>
                <p className="text-sm text-muted-foreground leading-relaxed">
                  GynoVision AI is a research prototype developed for academic demonstration and educational purposes. It has not undergone regulatory approval for clinical use. All predictions generated by this system are intended to supplement — not replace — professional medical judgment. Users must not rely on this tool for clinical decision-making without appropriate validation and medical oversight.
                </p>
              </div>
            </div>
          </GlassCard>

          {/* Privacy & Ethics */}
          <GlassCard hover={false}>
            <h3 className="font-display font-semibold text-foreground mb-3">Privacy & Ethics Notice</h3>
            <ul className="space-y-3 text-sm text-muted-foreground">
              <li className="flex items-start gap-2">
                <span className="w-1.5 h-1.5 rounded-full bg-primary shrink-0 mt-2" />
                No patient data is stored, transmitted, or retained by this application.
              </li>
              <li className="flex items-start gap-2">
                <span className="w-1.5 h-1.5 rounded-full bg-primary shrink-0 mt-2" />
                All uploaded images are processed locally and discarded after classification.
              </li>
              <li className="flex items-start gap-2">
                <span className="w-1.5 h-1.5 rounded-full bg-primary shrink-0 mt-2" />
                The system complies with academic research ethics guidelines.
              </li>
              <li className="flex items-start gap-2">
                <span className="w-1.5 h-1.5 rounded-full bg-primary shrink-0 mt-2" />
                Model training data sourced from publicly available, de-identified datasets.
              </li>
            </ul>
          </GlassCard>

          {/* Contact */}
          <GlassCard hover={false}>
            <h3 className="font-display font-semibold text-foreground mb-4">Contact Information</h3>
            <div className="space-y-4">
              <div className="flex items-center gap-3">
                <div className="w-9 h-9 rounded-lg bg-primary/10 flex items-center justify-center">
                  <Mail className="w-4 h-4 text-primary" />
                </div>
                <div>
                  <p className="text-sm font-medium text-foreground">Email</p>
                  <p className="text-xs text-muted-foreground">research@gynovision-ai.edu</p>
                </div>
              </div>
              <div className="flex items-center gap-3">
                <div className="w-9 h-9 rounded-lg bg-primary/10 flex items-center justify-center">
                  <MapPin className="w-4 h-4 text-primary" />
                </div>
                <div>
                  <p className="text-sm font-medium text-foreground">Institution</p>
                  <p className="text-xs text-muted-foreground">Department of Computer Science & Medical Informatics</p>
                </div>
              </div>
            </div>
          </GlassCard>
        </div>
      </div>
    </div>
  );
};

export default Contact;
