import jsPDF from "jspdf";

interface ReportData {
  prediction: string;
  confidence: number;
  classProbabilities: Record<string, number>;
}

const RECOMMENDATIONS: Record<string, { interpretation: string; riskLevel: string; actions: string[] }> = {
  "Superficial-Intermediate": {
    interpretation: "Normal mature squamous epithelial cells with no evidence of abnormality.",
    riskLevel: "Low",
    actions: [
      "Continue routine cervical screening as per guidelines",
      "No immediate medical intervention required",
    ],
  },
  Parabasal: {
    interpretation: "Immature cells, commonly associated with hormonal changes, atrophy, or mild inflammation.",
    riskLevel: "Low",
    actions: [
      "Routine screening recommended",
      "If present in high numbers: evaluate for hormonal imbalance or inflammation",
      "Clinical correlation may be required",
    ],
  },
  Metaplastic: {
    interpretation: "Cells undergoing normal transformation in the cervical epithelium (transformation zone).",
    riskLevel: "Low",
    actions: [
      "No treatment required",
      "Continue routine Pap smear screening",
      "Monitor only if atypical changes are suspected",
    ],
  },
  Koilocytotic: {
    interpretation: "Indicative of HPV infection, often associated with low-grade squamous intraepithelial lesions (LSIL).",
    riskLevel: "Moderate",
    actions: [
      "Perform HPV DNA testing",
      "Repeat Pap smear in 6–12 months",
      "Consider colposcopy if high-risk HPV is detected",
      "Consider colposcopy if abnormality persists",
    ],
  },
  Dyskeratotic: {
    interpretation: "Abnormal keratinized cells associated with precancerous changes and possible high-grade lesions (HSIL).",
    riskLevel: "High",
    actions: [
      "Immediate colposcopic evaluation",
      "Biopsy for confirmation",
      "Close clinical follow-up and management",
      "Treatment based on histopathological findings",
    ],
  },
};

export function generateCervicalReport(data: ReportData) {
  const doc = new jsPDF();
  const margin = 20;
  let y = margin;
  const pageWidth = doc.internal.pageSize.getWidth();
  const contentWidth = pageWidth - margin * 2;

  const addLine = (text: string, size: number, bold = false, color: [number, number, number] = [255, 255, 255]) => {
    doc.setFontSize(size);
    doc.setFont("helvetica", bold ? "bold" : "normal");
    doc.setTextColor(...color);
    const lines = doc.splitTextToSize(text, contentWidth);
    doc.text(lines, margin, y);
    y += lines.length * size * 0.45 + 2;
  };

  // Dark background
  doc.setFillColor(15, 15, 20);
  doc.rect(0, 0, pageWidth, doc.internal.pageSize.getHeight(), "F");

  // Header
  addLine("Cervical Cytology Report", 20, true, [130, 180, 255]);
  y += 2;
  addLine(`Generated: ${new Date().toLocaleString()}`, 9, false, [150, 150, 160]);
  y += 8;

  // Divider
  doc.setDrawColor(60, 60, 80);
  doc.line(margin, y, pageWidth - margin, y);
  y += 10;

  // Classification result
  addLine("Classification Result", 14, true, [130, 180, 255]);
  y += 2;
  addLine(`Predicted Cell Type: ${data.prediction}`, 11, true);
  addLine(`Model Confidence: ${(data.confidence * 100).toFixed(1)}%`, 11, false, [200, 200, 210]);
  y += 6;

  // Class probabilities
  addLine("Class Probabilities", 14, true, [130, 180, 255]);
  y += 2;
  const sorted = Object.entries(data.classProbabilities).sort(([, a], [, b]) => b - a);
  for (const [cls, prob] of sorted) {
    const isPredicted = cls === data.prediction;
    const color: [number, number, number] = isPredicted ? [255, 255, 255] : [160, 160, 170];
    addLine(`  ${cls}: ${(prob * 100).toFixed(1)}%${isPredicted ? "  ◄" : ""}`, 10, isPredicted, color);
  }
  y += 6;

  // Clinical recommendation
  const rec = RECOMMENDATIONS[data.prediction];
  if (rec) {
    doc.setDrawColor(60, 60, 80);
    doc.line(margin, y, pageWidth - margin, y);
    y += 10;

    addLine("Clinical Recommendation", 14, true, [130, 180, 255]);
    y += 2;
    addLine(`Risk Level: ${rec.riskLevel}`, 11, true,
      rec.riskLevel === "High" ? [255, 100, 100] : rec.riskLevel === "Moderate" ? [250, 200, 80] : [100, 220, 130]);
    y += 2;
    addLine("Interpretation:", 10, true, [200, 200, 210]);
    addLine(rec.interpretation, 10, false, [180, 180, 190]);
    y += 4;
    addLine("Recommended Actions:", 10, true, [200, 200, 210]);
    for (const action of rec.actions) {
      addLine(`  •  ${action}`, 10, false, [180, 180, 190]);
    }
  }

  // Disclaimer
  y += 10;
  doc.setDrawColor(60, 60, 80);
  doc.line(margin, y, pageWidth - margin, y);
  y += 8;
  addLine("Disclaimer", 10, true, [120, 120, 130]);
  addLine(
    "This report is generated by an AI model for educational and research purposes only. It is NOT a substitute for professional medical diagnosis. Always consult a qualified healthcare provider.",
    8, false, [120, 120, 130]
  );

  doc.save(`cervical-cytology-report-${new Date().toISOString().slice(0, 10)}.pdf`);
}
