import { motion } from "framer-motion";
import { Brain, Database, Cpu, Shield, BookOpen, Layers } from "lucide-react";
import PageHeader from "@/components/PageHeader";
import GlassCard from "@/components/GlassCard";

const About = () => {
  const technologies = [
    { icon: <Cpu className="w-5 h-5 text-primary" />, name: "Deep Learning", desc: "CNN architectures for cytology image classification" },
    { icon: <Database className="w-5 h-5 text-medical-teal" />, name: "TCGA Database", desc: "The Cancer Genome Atlas molecular profiling data" },
    { icon: <Layers className="w-5 h-5 text-medical-indigo" />, name: "Ensemble Models", desc: "Multi-model clinical risk prediction pipelines" },
    { icon: <Shield className="w-5 h-5 text-risk-moderate" />, name: "Ethics-First", desc: "Built for decision support, not autonomous diagnosis" },
  ];

  const datasets = [
    { name: "TCGA-UCEC", description: "Uterine Corpus Endometrial Carcinoma – molecular subtypes and clinical outcomes" },
    { name: "SipakMed", description: "Pap smear cytology image dataset for cervical cell classification" },
    { name: "Clinical Registry Data", description: "Curated clinical features from gynecological oncology databases" },
  ];

  return (
    <div className="min-h-screen pt-24 pb-16">
      <div className="container mx-auto px-4">
        <PageHeader
          icon={<BookOpen className="w-7 h-7 text-primary" />}
          title="About GynoVision AI"
          subtitle="A multimodal AI platform designed to support gynecological cancer assessment through clinical, molecular, and imaging data."
        />

        <div className="max-w-4xl mx-auto space-y-12">
          {/* Mission */}
          <GlassCard hover={false}>
            <h2 className="font-display text-xl font-semibold text-foreground mb-4">Our Mission</h2>
            <p className="text-muted-foreground leading-relaxed">
              GynoVision AI aims to bridge the gap between advanced computational research and clinical practice in gynecological oncology. By integrating multiple AI modalities — clinical risk models, molecular subtype classifiers, and deep learning image analysis — we provide a unified decision support platform that enhances clinician capabilities while maintaining the highest standards of medical ethics and interpretability.
            </p>
          </GlassCard>

          {/* Multimodal Approach */}
          <div>
            <motion.h2
              initial={{ opacity: 0 }}
              whileInView={{ opacity: 1 }}
              viewport={{ once: true }}
              className="font-display text-xl font-semibold text-foreground mb-6 text-center"
            >
              Multimodal AI Approach
            </motion.h2>
            <div className="grid sm:grid-cols-2 gap-4">
              {technologies.map((tech, i) => (
                <GlassCard key={tech.name} delay={i * 0.1} className="flex items-start gap-4">
                  <div className="w-10 h-10 rounded-xl bg-primary/10 flex items-center justify-center shrink-0">
                    {tech.icon}
                  </div>
                  <div>
                    <h3 className="font-display font-semibold text-foreground text-sm">{tech.name}</h3>
                    <p className="text-xs text-muted-foreground mt-1">{tech.desc}</p>
                  </div>
                </GlassCard>
              ))}
            </div>
          </div>

          {/* Datasets */}
          <GlassCard hover={false}>
            <h2 className="font-display text-xl font-semibold text-foreground mb-4">Datasets Used</h2>
            <div className="space-y-4">
              {datasets.map((ds) => (
                <div key={ds.name} className="border-l-2 border-primary/30 pl-4">
                  <h4 className="font-display font-semibold text-sm text-foreground">{ds.name}</h4>
                  <p className="text-xs text-muted-foreground mt-0.5">{ds.description}</p>
                </div>
              ))}
            </div>
          </GlassCard>

          {/* Disclaimer */}
          <GlassCard hover={false} className="border-primary/20">
            <h2 className="font-display text-xl font-semibold text-foreground mb-3">Academic & Ethical Disclaimer</h2>
            <p className="text-sm text-muted-foreground leading-relaxed">
              GynoVision AI is developed for academic research and educational demonstration purposes. It is not intended for clinical deployment without proper regulatory approval and clinical validation. All predictions are generated by machine learning models and must be interpreted by qualified medical professionals. This system emphasizes decision support, not autonomous diagnosis.
            </p>
          </GlassCard>
        </div>
      </div>
    </div>
  );
};

export default About;
